samples:
  - GR_untreated_1
  - GR_untreated_2
  - GR_Dexa_1
  - GR_Dexa_2
  - FOXA1_untreated_1
  - FOXA1_untreated_2
  - FOXA1_Dexa_1
  - FOXA1_Dexa_2
# control_files:
#   sub1: 'ctrl'
#   sub2: 'ctrl'
#   sub3: 'ctrl'
# reads:
#   - r1
#   - r2
# Select one of the following: bwa or bowtie2 or HISAT2 
chosen_aligner: bwa
# Select one of the following: narrrowPeak or broadPeak
#chosen_peaks: narrowPeak
# Select one of the following: hg38, hg19, mm19
genome_version: hg38
sequencing:
  # Select one of the following: single or paired
  type: single
  length: 60