# Paths
fastq_dir: path/to/fastq/files                             #path/to/fastq/files
output_dir: path/to/output                                 #path/to/output
#path/to/reference/genome.fa, it also looks for indexed files of each aligner there
ref_genome: path/to/reference/genome.fa

# Sequencing type (paired or single)
seq_type: paired 

# Chosen aligner (bwa or bowtie2)
aligner: bwa

# Samples (add your sample names here)
# 1. if it starts with a number add quotes to the sample name
# 2. The script assumes your files are: single-end.fastq.gz -> single-end is the sample name
#         or paired-end_R1.fastq.gz, paired-end_R2.fastq.gz -> paired-end is the sample name
samples:
  - sample_1
  - sample_2
  - sample_3
  - sample_4
